# Generated by Django 3.2.10 on 2022-06-21 10:25

from django.db import migrations, models
import uuid
import vanoma_api_utils.django.fields
import vanoma_api_utils.django.validators


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "staff_id",
                    vanoma_api_utils.django.fields.PrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    vanoma_api_utils.django.fields.StringField(max_length=40),
                ),
                (
                    "last_name",
                    vanoma_api_utils.django.fields.StringField(max_length=40),
                ),
                (
                    "phone_number",
                    vanoma_api_utils.django.fields.PhoneNumberField(
                        max_length=40,
                        unique=True,
                        validators=[vanoma_api_utils.django.validators.validate_number],
                    ),
                ),
                (
                    "status",
                    vanoma_api_utils.django.fields.StringField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("PENDING", "PENDING"),
                            ("INACTIVE", "INACTIVE"),
                        ],
                        default="PENDING",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff",
            },
        ),
    ]
