# Generated by Django 3.2.10 on 2022-03-18 15:42

from django.db import migrations, models
import django.db.models.deletion
import delivery_api.deliveries.utils.functions
import uuid
import vanoma_api_utils.django.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "assignment_id",
                    vanoma_api_utils.django.fields.PrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "package_id",
                    vanoma_api_utils.django.fields.StringField(max_length=40),
                ),
                (
                    "status",
                    vanoma_api_utils.django.fields.StringField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("COMPLETED", "COMPLETED"),
                            ("EXPIRED", "EXPIRED"),
                            ("CANCELED", "CANCELED"),
                        ],
                        max_length=40,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="drivers.driver",
                    ),
                ),
                (
                    "driver_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="drivers.location",
                    ),
                ),
            ],
            options={
                "db_table": "assignment",
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "stop_id",
                    vanoma_api_utils.django.fields.PrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_id",
                    vanoma_api_utils.django.fields.StringField(max_length=40),
                ),
                ("ranking", models.PositiveSmallIntegerField(null=True)),
                ("depart_by", models.DateTimeField(null=True)),
                ("arrive_by", models.DateTimeField(null=True)),
                ("departed_at", models.DateTimeField(null=True)),
                ("arrived_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "stop",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    vanoma_api_utils.django.fields.PrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    vanoma_api_utils.django.fields.StringField(
                        choices=[("PICK_UP", "PICK_UP"), ("DROP_OFF", "DROP_OFF")],
                        max_length=40,
                    ),
                ),
                ("completed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="deliveries.assignment",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="deliveries.stop",
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="Delay",
            fields=[
                (
                    "delay_id",
                    vanoma_api_utils.django.fields.PrimaryKeyField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    vanoma_api_utils.django.fields.StringField(
                        choices=[("STOP", "STOP"), ("ASSIGNMENT", "ASSIGNMENT")],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    vanoma_api_utils.django.fields.StringField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("JUSTIFIED", "JUSTIFIED"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "justification",
                    models.FileField(
                        upload_to=delivery_api.deliveries.utils.functions.resolve_upload_to
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="deliveries.assignment",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="drivers.driver",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="deliveries.stop",
                    ),
                ),
            ],
            options={
                "db_table": "delay",
            },
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("stop", "assignment", "type"),
                name="unique_task_type_for_assignment_and_stop",
            ),
        ),
    ]
