# Generated by Django 3.2.10 on 2022-05-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="driver_location",
            new_name="confirmation_location",
        ),
    ]
