# Generated by Django 3.2.10 on 2022-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_rename_driver_location_assignment_confirmation_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stop",
            name="address_id",
        ),
        migrations.AddField(
            model_name="stop",
            name="latitude",
            field=models.FloatField(default=-1.9353231),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stop",
            name="longitude",
            field=models.FloatField(default=30.0692974),
            preserve_default=False,
        ),
    ]
