# Generated by Django 3.2.10 on 2022-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_auto_20220603_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
