# Generated by Django 3.2.10 on 2022-06-07 12:27

from typing import Any
from django.db import migrations


def populate_stop_completed_at(apps: Any, schema_editor: Any) -> None:
    Stop = apps.get_model("deliveries", "Stop")
    for stop in Stop.objects.all():
        if not stop.tasks.filter(completed_at__isnull=True).exists():
            task = stop.tasks.first()
            if task:
                stop.completed_at = task.completed_at
                stop.save()


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_stop_completed_at"),
    ]

    operations = [
        migrations.RunPython(populate_stop_completed_at),
    ]
