# Generated by Django 3.2.10 on 2022-06-17 15:11

from django.db import migrations
import vanoma_api_utils.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_populate_stop_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="type",
            field=vanoma_api_utils.django.fields.StringField(
                choices=[("MANUAL", "MANUAL"), ("AUTOMATIC", "AUTOMATIC")],
                default="AUTOMATIC",
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
