name: vanoma_driver
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  android_intent_plus: ^3.1.1+1
  connectivity_plus: ^2.0.2
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.7.1
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^4.2.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  geolocator: ^8.0.5
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  provider: ^6.0.1
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10
  onesignal_flutter: ^3.1.0
  tuple: ^2.0.0
  sentry_flutter: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.4
flutter_native_splash:
  color: '#d61b53'
  image: 'assets/images/logo.png'
  color_dark: '#0c0004'

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
