# Generated by Django 3.2.10 on 2022-05-25 16:34

from django.db import migrations
import vanoma_api_utils.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="status",
            field=vanoma_api_utils.django.fields.StringField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("PENDING", "PENDING"),
                    ("INACTIVE", "INACTIVE"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
    ]
