# Generated by Django 3.2.10 on 2022-06-01 17:34

from django.db import migrations
import uuid
import vanoma_api_utils.django.fields
import vanoma_api_utils.django.validators


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_driver_second_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="driver_id",
            field=vanoma_api_utils.django.fields.PrimaryKeyField(
                default=uuid.uuid4,
                editable=False,
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=vanoma_api_utils.django.fields.PhoneNumberField(
                max_length=40,
                unique=True,
                validators=[vanoma_api_utils.django.validators.validate_number],
            ),
        ),
    ]
