# Generated by Django 3.2.10 on 2022-07-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_auto_20220601_1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="is_full_time",
            field=models.BooleanField(default=False),
        ),
    ]
