class DRIVER_STATUS:
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    INACTIVE = "INACTIVE"

    ALL = [
        (ACTIVE, ACTIVE),
        (PENDING, PENDING),
        (INACTIVE, INACTIVE),
    ]


class LOCATION_ACCESS_STATUS:
    DENIED = "DENIED"
    ALLOWED_ALWAYS = "ALLOWED_ALWAYS"
    ALLOWED_WHEN_IN_USE = "ALLOWED_WHEN_IN_USE"

    ALL = [
        (DENIED, DENIED),
        (ALLOWED_ALWAYS, ALLOWED_ALWAYS),
        (ALLOWED_WHEN_IN_USE, ALLOWED_WHEN_IN_USE),
    ]
